#!/bin/sh
# test/check.t - `muster check`: the declared policy and the declared
# INTENT, squared against this box. Policy: profiles over sets of repos,
# expanded against the filesystem. Intent: who drives each profile
# (systemd, external, manual), and whether the units and the runs agree.
#
# The exit is a contract an integrator maps onto apply and check:
# 0 all well, 1 drift only (`schedule install` repairs it), 3 a fault (no
# install repairs it), 2 an invalid config.
#
# Prints `ok   check (N checks)` or `FAIL check:` and every failure.
set -u

H_NAME=check
# shellcheck source=SCRIPTDIR/harness_lib
. "$(dirname -- "$0")/harness_lib"
h_stub_systemctl

export MUSTER_STATE_DIR="$_T/state"
C=$_T/cfg
mkdir -p "$C"
for _n in alpha beta gamma hush hwdp; do mkrepo "$_n"; done
export MUSTER_CONFIG="$C/repos"
ck() {   # <config lines...>: write them, run check
  printf '%s\n' "$@" | h_cfg "$MUSTER_CONFIG"
  OUT=$("$MUSTER" check 2>"$_T/err" </dev/null)
  RC=$?
  ERR=$(cat "$_T/err")
}
# The POLICY tests run undriven, so no run or unit can be a finding.
pol() { ck 'driver manual' "$@"; }
row() { printf '%s\n' "$OUT" | awk -v p="$1" '$1 == p'; }
none() { test -z "$(printf '%s\n' "$OUT" | grep -E '^(fault|drift) ')"; }

# === policy: profiles over sets of repos =====================================
pol 'profile watch owed -' 'profile canon catch-up - alpha' \
   'profile pkgs catch-up - /h.*/'
expect_rc 0 "disjoint acting profiles, overlapping observe-only"
assert "no selectors: the whole set" has "$(row watch)" "all (5)"
assert "a literal selects that repo" \
  test "$(row canon | awk '{print $5}')" = alpha
assert "a pattern selects by whole name" has "$(row pkgs)" "hush hwdp"
assert "a pattern is anchored: /h.*/ does not take alpha" \
  test -z "$(row pkgs | grep alpha)"
assert "coherent: no findings" none

pol 'profile a catch-up - alpha beta' 'profile b catch-up - /b.*|gamma/'
expect_rc 3 "two acting profiles share a repo: a FAULT"
assert "overlap names both profiles and the repo" \
  has "$OUT" "fault  overlap    a and b both act on beta"
pol 'profile a catch-up -' 'profile b catch-up - hush'
expect_rc 3 "a whole-set acting profile overlaps any other acting one"
pol 'profile a owed - alpha' 'profile b owed - alpha' 'profile c survey - alpha'
expect_rc 0 "observe-only profiles may overlap freely"
pol 'profile a catch-up - alpha' 'profile b owed - alpha'
expect_rc 0 "an acting and an observing profile may share a repo"

pol 'profile a owed - alpha nosuch'
expect_rc 3 "a literal that is not a repo here"
assert "missing named" has "$OUT" "fault  missing    a: nosuch is not a repo"
mkdir "$ROOT/plaindir"
pol 'profile a owed - plaindir'
expect_rc 3 "a literal naming a non-repo directory"
pol 'profile a owed - /zz.*/'
expect_rc 3 "a profile that selects nothing"
assert "empty named" has "$OUT" "fault  empty      a: selects no repos"
assert "the dead pattern is a note" has "$OUT" "note   unmatched  a: /zz.*/"
pol 'profile a owed - alpha /zz.*/'
expect_rc 0 "a pattern matching nothing beside a live selector: a note"
if [ -n "$CAN_LOCK" ]; then
  mkrepo locked
  chmod 000 "$ROOT/locked"
  pol 'profile a owed - locked'
  expect_rc 0 "an unreadable literal is THERE, so not missing"
  chmod 755 "$ROOT/locked"
fi

for _bad in 'profile a owed - //' 'profile a owed - /a[/' \
    'profile a owed - a/b' 'profile a owed - a,b' 'driver cron' \
    'profile a owed - driver=cron' \
    'profile a owed 1h driver=systemd x driver=manual'; do
  ck 'driver manual' "$_bad"
  expect_rc 2 "invalid config: $_bad"
done
ck 'driver manual' 'driver systemd'
expect_rc 2 "more than one driver line"

# === intent: manual ==========================================================
pol 'profile a owed 1h alpha'
expect_rc 3 "manual with an interval: nothing will honour it"
assert "the incoherence is named" has "$OUT" "fault  interval   a: every 1h"
pol 'profile a owed - alpha'
expect_rc 0 "manual, never run: on demand, not a finding"
assert "no driver note once one is declared" \
  test -z "$(printf '%s\n' "$OUT" | grep 'note   driver')"
mkdir -p "$HOME/.config/systemd/user"
_mark='# generated by muster schedule: edit the profile, not this file'
printf '%s\n' "$_mark" > "$HOME/.config/systemd/user/muster-a.timer"
pol 'profile a owed - alpha'
expect_rc 1 "a muster timer for a MANUAL profile: drift, install removes it"
assert "unwanted named" has "$OUT" "drift  unwanted   muster-a.timer"
"$MUSTER" schedule install >/dev/null 2>&1
pol 'profile a owed - alpha'
expect_rc 0 "after install the unwanted unit is gone"
# Run once by hand, long ago: a manual profile has no cadence to miss.
"$MUSTER" run a >/dev/null 2>&1
sed -i.bak 's/^finished=.*/finished=1000/' "$_T/state/a/latest.meta"
rm -f "$_T/state/a/latest.meta.bak"
pol 'profile a owed - alpha'
expect_rc 0 "a manual profile whose last run is old is NOT stale"
rm -f "$_T/state/a/latest.meta" "$_T/state/a/latest.records" \
  "$_T/state/a/latest.err"

# === intent: systemd =========================================================
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 1 "systemd, freshly declared, nothing installed: drift only"
assert "missing units are drift" has "$OUT" "drift  missing    muster-a.timer"
assert "a fresh intent is not yet 'never'" \
  test -z "$(printf '%s\n' "$OUT" | grep 'fault  never')"
"$MUSTER" schedule install >/dev/null 2>&1
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 0 "apply then check converges: installed, pending"
"$MUSTER" run a >/dev/null 2>&1
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 0 "installed and run"
# The run stops coming: stale.
sed -i.bak 's/^finished=.*/finished=1000/' "$_T/state/a/latest.meta"
rm -f "$_T/state/a/latest.meta.bak"
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 3 "a driven profile whose runs stopped: a FAULT"
assert "stale named" has "$OUT" "fault  stale      a:"
# ...UNLESS SYSTEMD SAYS THE DRIVER IS ALIVE. After a suspend the wall
# clock runs ahead of the timers (they count awake time only), so an old
# run beside a timer due within its interval is a sleep, not a stop.
_tj() {   # <next, seconds from now>: plant the timer list systemd reports
  printf '[{"next":%s000000,"left":0,"last":0,"passed":0,' \
    "$(( $(date +%s) + $1 ))" > "$H_SYS/timers.json"
  printf '"unit":"muster-a.timer","activates":"muster-a.service"}]\n' \
    >> "$H_SYS/timers.json"
}
_tj 1800
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 0 "after a suspend: old run, timer due within the hour, no fault"
assert "after a suspend: not called stale" \
  test -z "$(printf '%s\n' "$OUT" | grep 'fault  stale')"
_tj -60
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 3 "a timer whose next firing is PAST (a hung run): still stale"
_tj 10800
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 3 "a timer due further off than its interval: still stale"
_tj 1800
echo exit-code > "$H_SYS/result.muster-a.service"
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 3 "a live timer firing a FAILING service: still stale"
rm -f "$H_SYS/result.muster-a.service"
printf '[]\n' > "$H_SYS/timers.json"
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 3 "systemd reports no such timer: still stale"
rm -f "$H_SYS/timers.json"
# Never run although the intent is old: never.
rm -f "$_T/state/a/latest.meta" "$_T/state/a/latest.records" \
  "$_T/state/a/latest.err"
touch -t 200001010000 "$HOME/.config/systemd/user/muster-a.timer" \
  "$MUSTER_CONFIG"
OUT=$("$MUSTER" check 2>/dev/null); RC=$?
expect_rc 3 "an old intent that has never run"
assert "never named" has "$OUT" "fault  never      a:"
_tj 1800
OUT=$("$MUSTER" check 2>/dev/null); RC=$?
expect_rc 0 "never run, but systemd has it due within the hour: pending"
rm -f "$H_SYS/timers.json"
"$MUSTER" run a >/dev/null 2>&1
ck 'driver systemd' 'profile a owed - alpha'
expect_rc 3 "systemd with no interval: nothing to judge runs against"
assert "named" has "$OUT" "fault  interval   a: driven by systemd"
ck 'driver systemd' 'profile a owed 1h alpha'
# A last run that could not run.
sed -i.bak 's/^exit=.*/exit=2/' "$_T/state/a/latest.meta"
rm -f "$_T/state/a/latest.meta.bak"
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 3 "a driven profile whose last run failed"
assert "failed named" has "$OUT" "fault  failed     a:"
"$MUSTER" run a >/dev/null 2>&1
# A disabled timer is drift; drift beside a fault exits as the fault.
systemctl --user disable --now muster-a.timer
ck 'driver systemd' 'profile a owed 1h alpha'
expect_rc 1 "a disabled timer: drift"
ck 'driver systemd' 'profile a owed 1h alpha' 'profile z owed 1h nosuch'
expect_rc 3 "drift AND a fault: the fault decides the exit"
"$MUSTER" schedule install >/dev/null 2>&1

# === intent: external ========================================================
ck 'driver external' 'profile a owed 1h alpha'
expect_rc 1 "external: muster's own timer must not be there"
assert "named unwanted" has "$OUT" "drift  unwanted   muster-a.timer"
"$MUSTER" schedule install >/dev/null 2>&1
ck 'driver external' 'profile a owed 1h alpha'
expect_rc 0 "external, its runs current, no muster units"
sed -i.bak 's/^finished=.*/finished=1000/' "$_T/state/a/latest.meta"
rm -f "$_T/state/a/latest.meta.bak"
ck 'driver external' 'profile a owed 1h alpha'
expect_rc 3 "external whose driver stopped running it: muster still sees it"
assert "stale names the driver" has "$OUT" "its external driver has stopped"

# === per-profile override, and the undeclared default ========================
ck 'driver manual' 'profile a owed 1h driver=external alpha'
assert "a profile's driver= overrides the config's" \
  test "$(row a | awk '{print $4}')" = external
ck 'profile a owed - alpha'
assert "no driver declared: the check says what it assumed" \
  has "$OUT" "note   driver     none declared"

# === systemd wanted, and no systemd here =====================================
mkdir -p "$_T/nosysd"
for _f in /usr/bin/* /bin/*; do
  [ "${_f##*/}" = systemctl ] && continue
  [ -e "$_T/nosysd/${_f##*/}" ] || [ -h "$_T/nosysd/${_f##*/}" ] \
    || ln -s "$_f" "$_T/nosysd/${_f##*/}"
done
printf '%s\n' 'driver systemd' 'profile a owed 1h alpha' \
  | h_cfg "$MUSTER_CONFIG"
OUT=$(PATH=$_T/nosysd "$MUSTER" check 2>&1); RC=$?
expect_rc 3 "systemd wanted with no systemctl: a fault, install cannot help"
assert "named" has "$OUT" "fault  no-systemd"

cli() {
  OUT=$("$MUSTER" "$@" 2>"$_T/err" </dev/null)
  RC=$?
}
# === stores of profiles no longer declared: a note, never deleted ========
_cs=$_T/state
mkdir -p "$_cs/oldname/history" "$_cs/kept" "$_cs/root/home"
echo exit=0 > "$_cs/oldname/latest.meta"
echo exit=0 > "$_cs/kept/latest.meta"
echo placed > "$_cs/root/home/a.conf"
ck 'driver manual' 'profile kept owed - alpha'
expect_rc 0 "an orphan store is a note: the exit is unchanged"
assert "the orphan store is named, with its size" \
  has "$OUT" "note   store      oldname: the runs of a profile no longer"
assert "a declared profile's store is not named" lacks "$OUT" "store      kept"
assert "the placement mirror is not a profile store" \
  lacks "$OUT" "store      root"
assert "and the orphan is left exactly where it was" \
  test -f "$_cs/oldname/latest.meta"
rm -f "$_cs/oldname/latest.meta" "$_cs/kept/latest.meta" \
  "$_cs/root/home/a.conf"
rmdir "$_cs/oldname/history" "$_cs/oldname" "$_cs/kept" "$_cs/root/home" \
  "$_cs/root"

cli check extra
expect_rc 2 "check takes no arguments"

h_verdict
