#!/bin/sh
# test/schedule.t - `muster schedule`: generated units, install / check /
# remove, drift both ways, orphans, and units muster did not write.
#
# systemctl is a STUB first on PATH that keeps enabled/active state in the
# scratch dir, and the unit dir is proven to be inside the scratch dir
# before anything runs: a test must never touch the real user manager.
#
# Prints `ok   schedule (N checks)` or `FAIL schedule:` and every failure.
set -u

H_NAME=schedule
# shellcheck source=SCRIPTDIR/harness_lib
. "$(dirname -- "$0")/harness_lib"

export MUSTER_STATE_DIR="$_T/state"
h_stub_systemctl
UNITS=$H_UNITS
SYS=$H_SYS
assert "the stub is the systemctl in use" \
  test "$(command -v systemctl)" = "$_T/stub/systemctl"

C=$_T/cfg
mkdir -p "$C"
printf '%s\n' 'driver systemd' 'profile watch owed 30m' \
  'profile sync catch-up 2h' > "$C/two"
export MUSTER_CONFIG="$C/two"
cli() {
  OUT=$("$MUSTER" "$@" 2>"$_T/err" </dev/null)
  RC=$?
  ERR=$(cat "$_T/err")
}
enabled() { [ -e "$SYS/enabled.muster-$1.timer" ]; }

# === before install, check reports every gap ===============================
cli schedule check
expect_rc 1 "check before install"
assert "check: the missing service" has "$OUT" "missing    muster-watch.service"
assert "check: the missing timer" has "$OUT" "missing    muster-sync.timer"
assert "check: the disabled timer" has "$OUT" "disabled   muster-watch.timer"
assert "check: the inactive timer" has "$OUT" "inactive   muster-sync.timer"
assert "check wrote nothing" test ! -e "$UNITS/muster-watch.service"

# === install ================================================================
cli schedule install
expect_rc 0 "install"
assert "install: wrote the service" has "$OUT" "wrote      muster-watch.service"
assert "install: wrote the timer" has "$OUT" "wrote      muster-sync.timer"
assert "install: enabled watch" enabled watch
assert "install: enabled sync" enabled sync
assert "install: reloaded the manager" \
  has "$(cat "$SYS/log")" "--user daemon-reload"
cli schedule check
expect_rc 0 "check after install"
assert "check after install says so" has "$OUT" "ok         the units match"

# The units themselves.
SVC=$(cat "$UNITS/muster-watch.service")
TMR=$(cat "$UNITS/muster-watch.timer")
assert "service: first line marks it as muster's" \
  starts "$SVC" "# generated by muster schedule"
assert "service: runs the profile with this muster" \
  has "$SVC" "ExecStart=\"$(cd "$HERE/../bin" && pwd -P)/muster\" run watch"
assert "service: the config is baked in" \
  has "$SVC" "Environment=\"MUSTER_CONFIG=$C/two\""
assert "service: the state dir is baked in" \
  has "$SVC" "Environment=\"MUSTER_STATE_DIR=$_T/state\""
assert "service: oneshot" has "$SVC" "Type=oneshot"
assert "timer: the profile's interval" has "$TMR" "OnUnitActiveSec=30m"
assert "timer: wanted by timers.target" has "$TMR" "WantedBy=timers.target"

# The generated service actually works: run its ExecStart with its env.
mkrepo one
_bin=$(sed -n 's/^ExecStart="\(.*\)" run .*$/\1/p' \
  "$UNITS/muster-watch.service")
_cfg=$(sed -n 's/^Environment="MUSTER_CONFIG=\(.*\)"$/\1/p' \
  "$UNITS/muster-watch.service")
MUSTER_CONFIG=$_cfg "$_bin" run watch >/dev/null 2>&1
assert "the unit's command runs the profile and stores it" \
  test -s "$_T/state/watch/latest.records"

# Idempotent: nothing rewritten the second time.
cli schedule install
expect_rc 0 "install again"
assert "install again: unchanged" has "$OUT" "unchanged  muster-watch.service"
assert "install again: nothing written" test -z "$(printf '%s\n' "$OUT" \
  | grep '^wrote')"

# === drift, both ways =======================================================
# The declared interval changed: the timer on disk is now wrong.
printf '%s\n' 'driver systemd' 'profile watch owed 1h' \
  'profile sync catch-up 2h' > "$C/two"
cli schedule check
expect_rc 1 "check after the interval changed"
assert "check: the changed timer differs" \
  has "$OUT" "differs    muster-watch.timer"
assert "check: the unchanged service does not" \
  test -z "$(printf '%s\n' "$OUT" | grep 'muster-watch.service')"
cli schedule install
assert "install: rewrote only the timer" \
  has "$OUT" "wrote      muster-watch.timer"
assert "install: the new interval" \
  has "$(cat "$UNITS/muster-watch.timer")" "OnUnitActiveSec=1h"

# Someone disabled a timer by hand.
systemctl --user disable --now muster-sync.timer
cli schedule check
expect_rc 1 "check with a disabled timer"
assert "check: names the disabled timer" \
  has "$OUT" "disabled   muster-sync.timer"
cli schedule install
assert "install re-enables it" enabled sync

# A profile was dropped: its units are orphans, reported then removed.
printf 'driver systemd\nprofile watch owed 1h\n' > "$C/two"
cli schedule check
expect_rc 1 "check with an orphaned profile"
assert "check: the orphan service" has "$OUT" "orphan     muster-sync.service"
assert "check: the orphan timer" has "$OUT" "orphan     muster-sync.timer"
cli schedule install
assert "install removed the orphan" test ! -e "$UNITS/muster-sync.timer"
assert "install disabled the orphan" eval '! enabled sync'
cli schedule check
expect_rc 0 "check once the orphan is gone"

# === a unit muster did not write is never touched ==========================
printf '[Timer]\nOnUnitActiveSec=5m\n' > "$UNITS/muster-mine.timer"
cli schedule check
expect_rc 0 "a hand-written muster-*.timer is not an orphan"
cli schedule install
assert "install left the hand-written unit" test -f "$UNITS/muster-mine.timer"

# === quoting what goes into a unit file =====================================
mkdir -p "$_T/odd%dir"
printf 'driver systemd\nprofile watch owed 1h\n' > "$_T/odd%dir/repos"
MUSTER_CONFIG=$_T/odd%dir/repos cli schedule install
expect_rc 0 "install with a % in the config path"
assert "a % is doubled for systemd" \
  has "$(cat "$UNITS/muster-watch.service")" "odd%%dir/repos"
mkdir -p "$_T/bad\"dir"
printf 'driver systemd\nprofile watch owed 1h\n' > "$_T/bad\"dir/repos"
MUSTER_CONFIG=$_T/bad\"dir/repos cli schedule install
expect_rc 2 "install refuses a value that would break the quoting"
assert "the refusal names the value" has "$ERR" "cannot put"
MUSTER_CONFIG=$C/two cli schedule install
printf 'driver systemd\nprofile we@b owed 1h\n' > "$C/at"
MUSTER_CONFIG=$C/at cli schedule install
expect_rc 2 "a profile name that would make a systemd template"

# === the notifier is baked as an absolute path ==============================
printf '#!/bin/sh\nexit 0\n' > "$_T/stub/notify-me"
chmod +x "$_T/stub/notify-me"
MUSTER_CONFIG=$C/two MUSTER_NOTIFY=notify-me cli schedule install
expect_rc 0 "install with a notifier found on PATH"
assert "the notifier is baked ABSOLUTE, not as a bare name" \
  has "$(cat "$UNITS/muster-watch.service")" \
  "Environment=\"MUSTER_NOTIFY=$_T/stub/notify-me\""
MUSTER_CONFIG=$C/two MUSTER_NOTIFY=no-such-notifier cli schedule install
expect_rc 2 "install refuses a notifier it cannot resolve"
assert "the refusal says why" has "$ERR" "does not resolve"
MUSTER_CONFIG=$C/two cli schedule install

# === overlapping acting profiles are never put on a timer ===================
printf '%s\n' 'driver systemd' 'profile a catch-up 1h' \
  'profile b catch-up 2h one' > "$C/over"
MUSTER_CONFIG=$C/over cli schedule install
expect_rc 2 "install refuses overlapping acting profiles"
assert "the refusal names them" has "$ERR" "a b one"
assert "nothing was written for them" test ! -e "$UNITS/muster-b.timer"
MUSTER_CONFIG=$C/two cli schedule install

# The notifier as a CONFIG fact: install bakes it, and a check from a
# shell with no MUSTER_NOTIFY computes the same unit (no false drift).
printf 'driver systemd\nprofile watch owed 1h\nnotify notify-me\n' > "$C/ntf"
MUSTER_CONFIG=$C/ntf cli schedule install
expect_rc 0 "install with the notifier declared in the config"
assert "the config's notifier is baked, absolute" \
  has "$(cat "$UNITS/muster-watch.service")" \
  "Environment=\"MUSTER_NOTIFY=$_T/stub/notify-me\""
(unset MUSTER_NOTIFY; MUSTER_CONFIG=$C/ntf "$MUSTER" schedule check) \
  >"$_T/ck" 2>&1
_rc=$?
assert "check from a plain shell: no false drift" test "$_rc" = 0
assert "check from a plain shell: says ok" has "$(cat "$_T/ck")" "ok"
printf '#!/bin/sh\nexit 0\n' > "$_T/stub/other-notify"
chmod +x "$_T/stub/other-notify"
MUSTER_NOTIFY=other-notify MUSTER_CONFIG=$C/ntf cli schedule install
assert "MUSTER_NOTIFY overrides the config" \
  has "$(cat "$UNITS/muster-watch.service")" "MUSTER_NOTIFY=$_T/stub/other"
for _bad in 'notify a b' 'notify'; do
  printf 'driver systemd\nprofile watch owed 1h\n%s\n' "$_bad" > "$C/nbad"
  MUSTER_CONFIG=$C/nbad cli schedule check
  expect_rc 2 "invalid notify line: $_bad"
done
printf 'notify a\nnotify b\n' > "$C/nbad"
MUSTER_CONFIG=$C/nbad cli schedule check
expect_rc 2 "two notify lines"
MUSTER_CONFIG=$C/two cli schedule install

# === remove =================================================================
cli schedule remove
expect_rc 0 "remove"
assert "remove: our units are gone" test ! -e "$UNITS/muster-watch.service"
assert "remove: our timer is disabled" eval '! enabled watch'
assert "remove: the hand-written unit stays" test -f "$UNITS/muster-mine.timer"
cli schedule check
expect_rc 1 "check after remove"

# === no systemd, and the command line =======================================
# shellcheck source=SCRIPTDIR/../lib/survey_lib
. "$HERE/../lib/survey_lib"
# shellcheck source=SCRIPTDIR/../lib/schedule_lib
. "$HERE/../lib/schedule_lib"
# shellcheck disable=SC2123  # emptying PATH is the point: no systemctl
_msg=$( (PATH=/nonexistent; _sc_systemd) 2>&1 ); _rc=$?
assert "no systemctl: fails" test "$_rc" = 1
assert "no systemctl: says what to do instead" has "$_msg" "muster run"
cli schedule
expect_rc 2 "schedule with no action"
cli schedule frob
expect_rc 2 "schedule with an unknown action"
cli schedule check extra
expect_rc 2 "schedule with an extra argument"

h_verdict
